name: github pages

on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
          QIITA_API_TOKEN: ${{ secrets.QIITA_API_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
